/*
 * MORTAR - MOlecule fRagmenTAtion fRamework
 * Copyright (C) 2025
 */
package de.unijena.cheminf.mortar.gradle.plugins

import de.unijena.cheminf.mortar.gradle.util.modifyMortarStartScripts

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.application.CreateStartScripts
import org.gradle.kotlin.dsl.named

/**
 * A Gradle plugin designed to configure and customize the start scripts for a Java application named
 * MORTAR. This plugin specializes in adjusting the runtime parameters, memory settings, and script
 * modifications for both Windows and Unix systems.
 *
 * The primary functionality includes:
 * - Configuring the standard `startScripts` task to align with MORTAR's default settings.
 * - Providing additional tasks with custom memory configurations through the `registerMortarStartScriptTask` method.
 * - Modifying the generated start scripts using the `modifyMortarStartScripts` function to tailor
 *   them to specific environments.
 *
 * Registered Tasks:
 * - `mortarStandardMemory`: Generates start scripts with standard memory configurations.
 * - `mortarHighMemory`: Generates start scripts with high memory configurations.
 *
 * Gradle properties:
 * - `mainClassName`: Defines the fully qualified name of the main class to be executed.
 * - `defaultHeapSize`: Specifies the initial and maximum heap size for default memory configurations.
 * - `highHeapSize`: Specifies the initial and maximum heap size for high memory configurations.
 * - `defaultMemoryOptimization`: Represents the JVM optimization variable for default memory configurations.
 * - `highMemoryOptimization`: Represents the JVM optimization variable for high memory configurations.
 *
 * @author Martin Urban
 */
class MortarStartScriptsPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        with(project) {
            val mainClassName = providers.gradleProperty("mainClassName")
            val defaultHeapSize = providers.gradleProperty("defaultHeapSize")
            val highHeapSize = providers.gradleProperty("highHeapSize")
            val defaultMemoryOptimization = providers.gradleProperty("defaultMemoryOptimization")
            val highMemoryOptimization = providers.gradleProperty("highMemoryOptimization")

            // Configure the standard startScripts task used by installDist
            tasks.named<CreateStartScripts>("startScripts") {
                applicationName = "MORTAR"
                mainClass.set(mainClassName.get())
                // Keep same classpath as generated by the Application plugin
                defaultJvmOpts = listOf("-Xms${defaultHeapSize.get()}", "-Xmx${defaultHeapSize.get()}")
                doLast {
                    modifyMortarStartScripts(windowsScript, unixScript, defaultMemoryOptimization.get())
                }
            }

            // Helper to register a CreateStartScripts task with post-processing
            fun registerMortarStartScriptTask(
                name: String,
                appName: String,
                optVar: String,
                heap: String
            ) = tasks.register(name, CreateStartScripts::class.java) {
                mainClass.set(mainClassName.get())
                // Reuse the classpath determined by the default startScripts task
                classpath = tasks.named<CreateStartScripts>("startScripts").get().classpath
                outputDir = layout.buildDirectory.dir("scripts").get().asFile
                applicationName = appName
                defaultJvmOpts = listOf("-Xms$heap", "-Xmx$heap")
                doLast {
                    modifyMortarStartScripts(windowsScript, unixScript, optVar)
                }
            }

            // Provide the two convenience tasks used by the project
            registerMortarStartScriptTask(
                name = "mortarStandardMemory",
                appName = "MORTAR",
                optVar = defaultMemoryOptimization.get(),
                heap = defaultHeapSize.get()
            )

            registerMortarStartScriptTask(
                name = "mortarHighMemory",
                appName = "MORTAR_20GB",
                optVar = highMemoryOptimization.get(),
                heap = highHeapSize.get()
            )
        }
    }
}
